### PR TITLE
issue1673 matrix profile

### PR DESCRIPTION
**Pull request by singhshraddha**
https://github.ibm.com/wiotp/monitoring-dashboard/issues/1673

Other PR for keeping packages cosistent
1. https://github.ibm.com/IoT-Enterprise/analytics-service-library/pull/334
2. https://github.ibm.com/IoT-Enterprise/analytics-service-pipeline/pull/204

### CODE REVIEW

**Review by pkohlmann — COMMENTED** [review]
1) Driver build of analytics-service-pipeline/library-as failed because of missing branch of iotfunctions with same name as analytics-service-pipeline/library-as. We have to make sure the changed versions do not cause pip into conflicts.
2) Do we have approval to add new module stumpy to our product?

**Comment by singhshraddha** [comment]
@pkohlmann 
1. For as-library: while the push build [#1601](https://travis.ibm.com/IoT-Enterprise/analytics-service-library/builds/42633932) failed, the PR build [#1602](https://travis.ibm.com/IoT-Enterprise/analytics-service-library/builds/42634369) passed. Similarly for pipeline the push build [#5457](https://travis.ibm.com/IoT-Enterprise/analytics-service-pipeline/builds/42634004) failed and PR build [#5458](https://travis.ibm.com/IoT-Enterprise/analytics-service-pipeline/builds/42634367) passed. Under the assumption that iotfunctions packages are the same across there three (all iotfunctions packages are in library and pipeline requirements) is this not enough evidence that pip won't cause conflicts?

2. No, `stumpy` is not pre-approved, but I was under the impression that we perform package checks after building images now. To be honest I'm not sure how this process works and if it's okay to include the package and ask for approval later or do we have to do this first

**Comment by pkohlmann** [comment]
@singhshraddha I'm not sure if I understand our build system completely: A successful PR-build of analytics service pipeline and of library tells us the new code works with the **current** iotfunction code. But you want to add new code to iotfunctions as well.  Do we have the proof analytics service pipeline and library work with the new code in iotfunctions? Maybe this is  a general issue we have with pull requests for iotfunctions because we do not check the compatibility with pipeline/library.

I have asked Wolfgang about the approval process for new components. There is no process for it. He will get in touch with you about it.

**Comment by sedgewickmm18** [comment]
I took the liberty to use the wicked tool for a pedigree search and couldn't find stumpy (no surprise)
https://taas.cloud.ibm.com/tools/wicked

CSAR scan of the stumpy code in github is found [here](https://ibm.box.com/s/wlx438zsp5fyw44smbp7lye3ibvf3a1t)
Result: Nothing suspicious, plain BSD-3 license.

I've asked Kelly to proceed with the open source approval process (OSSC).

**Review by pkohlmann — APPROVED** [review]

**Pull request merged**
