### PR TITLE
issue#527 : AnomalyGeneratorExtremeValue

### PR DESCRIPTION
**Pull request by ankit-jha**

### CODE REVIEW

**Comment by ankit-jha** [comment]
```sql
--'ExtremeAnomalyGenerator'
INSERT INTO IOTANALYTICS.CATALOG_FUNCTION (FUNCTION_ID,TENANT_ID,NAME,DESCRIPTION,MODULE_AND_TARGET_NAME,URL,CATEGORY,"INPUT","OUTPUT",INCREMENTAL_UPDATE,IMAGE) VALUES(CATALOG_FUNCTION_SEQ.nextval,'###_IBM_###','ExtremeAnomalyGenerator','
    This function generates extreme anomaly.
    ','extremeanomaly.extremeanomalygenerator.ExtremeAnomalyGenerator',NULL,'TRANSFORMER','[{"name":"input_item","description":"Item to base anomaly on","type":"DATA_ITEM","required":true,"dataType":"NUMBER","tags":[]},{"name":"size","description":"Size of extreme anomalies to be created. e.g. 10 will create 10x size extreme anomaly compared to the normal variance","type":"CONSTANT","required":true,"dataType":"NUMBER","tags":[]},{"name":"factor","description":"No. of extreme anomalies to be created","type":"CONSTANT","required":true,"dataType":"NUMBER","tags":[]}]','[{"name":"output_item","description":"Generated Item With Extreme anomalies","dataType":"NUMBER","tags":[]}]',NULL,NULL)
```

SQL For Migration

**Comment by sedgewickmm18** [comment]
Why do you still need to query the database ?

**Comment by ankit-jha** [comment]
> Why do you still need to query the database ?

I'm using that call to reinitialize count in case of KPI removal and recreation.

**Comment by sedgewickmm18** [comment]
Then you should save the function parms in cos. Then you could load from cos and only run the query if cosload results in None or the parms have changed

**Comment by ankit-jha** [comment]
> Then you should save the function parms in cos. Then you could load from cos and only run the query if cosload results in None or the parms have changed

cosload results will be none only for the first run. The true source to know if the KPI was recreated is to check if their are no records in derived metric table with that (output_item) key.

I'm not sure what I'm missing here and I'm also not clear about how to utilize function params.

**Comment by ankit-jha** [comment]
This PR has all 3 Generators 
https://github.com/ibm-watson-iot/functions/pull/135
We can merge only PR #135

**Pull request closed without merging**
