### PR TITLE
issue#644:Reverting back KMeans expression as it's now covered by scope

### PR DESCRIPTION
**Pull request by ankit-jha**

### CODE REVIEW

**Comment by ankit-jha** [comment]
@herleraja 
I have also moved all the existing expressions in **AnalyticsServiceDev** tenant to scope expression

**Comment by herleraja** [comment]
@ankit-jha We need to support the older version of the code. Our changes will break the customer who is already using the anomaly function. Do let me know the back support plan / migration plan.

Also check the production environment, how many people using this function then we can decide on a migration plan.

**Comment by ankit-jha** [comment]
We can migrate all the KMeans expression to scope expression in the database same time we push the 644 in production.

**Comment by ankit-jha** [comment]
@herleraja 
Does this mean https://github.com/ibm-watson-iot/functions/pull/243 that KMeans expression went into production today ?

**Comment by herleraja** [comment]
@ankit-jha No. That pull request I closed it. I did not merge it.

**Comment by ankit-jha** [comment]
We did a dependency check on US,UK and EU prod tenants. None of them have started using KMeans expression yet so the migration should not pose any issues.

**Pull request merged**
